import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>World Eye Foundation</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/wef_icon.png" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to World Eye Foundation!
				</h1>

				<p className={styles.description} style={{ paddingTop: "2em" }}>
					Our site is currently under construction...
				</p>

				<p className={styles.description}>
					In the meantime, here is the date:{" "}
					{new Date().toLocaleDateString()}
				</p>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
