import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import NavBar from "./components/Nav/NavBar";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>World Eye Foundation</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/wef_icon.png" />
			</Head>

			<NavBar />
			{/* <main className="container">
				<h1 className="display-1">Welcome to World Eye Foundation!</h1>

				<p className="display-3">
					Our site is currently under construction...
				</p>

				<p className="display-3">
					In the meantime, here is the date:{" "}
					{new Date().toLocaleDateString()}
				</p>
			</main>

			<footer className="container">
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer> */}
		</div>
	);
}
